sistema de musica
Alan5142/missile-toad pull request #28
Opened 2023-09-25 05:23 UTC by NapoElWapo

2023-09-25 05:58 UTC, Alan5142 requested changes

2023-09-25 05:58 UTC, Alan5142 commented on missile_toad/include/missile_toad/core/music.hpp
> +        [[nodiscard]] raylib::Music &get_music() noexcept;
Add documentation

2023-09-25 05:58 UTC, Alan5142 commented on missile_toad/main.cpp
> +    InitAudioDevice();
Consider adding a newline before and after this line,

2023-09-25 05:58 UTC, Alan5142 commented on missile_toad/main.cpp
> +    CloseAudioDevice();
Consider adding a newline before and after this line,

2023-09-25 05:59 UTC, NapoElWapo commented on missile_toad/include/missile_toad/core/music.hpp
> +        [[nodiscard]] raylib::Music &get_music() noexcept;
unu

2023-09-25 06:00 UTC, Alan5142 commented
@NapoElWapo add these
```yaml
-cppcoreguidelines-avoid-c-arrays
-modernize-avoid-c-arrays
```
to `.clang-tidy` file under the `Checks` section

2023-09-25 06:09 UTC, Alan5142 commented
* Create a component called AudioComponent, this component must contain a `entt::resource<missiletoad::core::Music>`. To do this, execute the command `python scripts/missiletoadcli.py component core::AudioComponent`

* Manually updating the music is tedious, that's why we should create a new System! `AudioSystem`, this system should get all components of type `AudioComponent` and update them in the `on_update` member function of the System. Add this system to the Scene class. To create this, execute the command `python scripts/missiletoadcli.py system core::AudioSystem`. See the following code to check where to create the instance.

https://github.com/Alan5142/missile-toad/blob/b92b32f15aa7534c91d1309fdbc3c4e19c565a15/missile_toad/src/core/scene.cpp#L72-L76

2023-09-28 02:23 UTC, Alan5142 requested changes
Call update for each music component in the music system.

2023-09-28 02:23 UTC, Alan5142 commented on missile_toad/include/missile_toad/core/music.hpp
> +        [[nodiscard]] raylib::Music &get_music() noexcept;
Seems good

2023-09-28 02:23 UTC, Alan5142 commented on missile_toad/include/missile_toad/core/systems/audio.system.hpp
Override on_update and call music update for all AudioComponents, that's the change I requested for AudioSystem.
Check entt::registry to get all components of certain type.

2023-09-28 02:29 UTC, NapoElWapo commented on missile_toad/include/missile_toad/core/systems/audio.system.hpp
why do you hate me so much

2023-09-28 03:14 UTC, Alan5142 commented on missile_toad/include/missile_toad/core/systems/audio.system.hpp
Change is not ready tho

2023-09-28 03:15 UTC, NapoElWapo commented on missile_toad/include/missile_toad/core/systems/audio.system.hpp
i'm, confused unu

2023-09-28 13:38 UTC, Alan5142 reviewed
Fix clang-tidy issues and we're done

2023-09-28 13:38 UTC, Alan5142 commented on missile_toad/include/missile_toad/core/systems/audio.system.hpp
If your destructor is empty, you could just `default`ed it.

I'm not going to get picky with it tho

2023-09-28 13:38 UTC, Alan5142 commented on missile_toad/src/core/systems/audio.system.cpp
Same as the other one, `default`ed would be better but not necessary

2023-09-28 13:42 UTC, Alan5142 approved these changes
Ok, just wait for the checks

2023-09-28 13:52 UTC, merged